def get_ligand_names_and_charges(space):

    if space == '1M':

        ligand_names = [
            'RUCBEY-subgraph-1', 'WECJIA-subgraph-3', 'KEYRUB-subgraph-1', 'NURKEQ-subgraph-2', 'MEBXUN-subgraph-1',
            'BIFMOV-subgraph-1', 'CUJYEL-subgraph-2', 'EZEXEM-subgraph-1', 'FOMVUB-subgraph-2', 'EFIHEJ-subgraph-3',
            'LETTEL-subgraph-1', 'KAKKIR-subgraph-3', 'BICRIQ-subgraph-3', 'UPEGAZ-subgraph-2', 'CEVJAP-subgraph-2',
            'BABTUT-subgraph-3', 'ZEJJEF-subgraph-3', 'KULGAZ-subgraph-2', 'CIGDAA-subgraph-1', 'HOVMIP-subgraph-3',
            'ULUSIE-subgraph-1', 'IBEKUV-subgraph-1', 'REQSUD-subgraph-2', 'BOSJIF-subgraph-1', 'GUVMEP-subgraph-0',
            'MAZJIJ-subgraph-0', 'OBONEA-subgraph-1', 'CORTOU-subgraph-2', 'LEVGUO-subgraph-2', 'REBWEB-subgraph-2',
            'DOGPAS-subgraph-1', 'IJIMIX-subgraph-1', 'PEJGAN-subgraph-1', 'BIFZEX-subgraph-0', 'IRIXUC-subgraph-3',
            'SAYGOO-subgraph-0', 'UROGIS-subgraph-1', 'MAQKEX-subgraph-1', 'LUQWUQ-subgraph-1', 'QAYDID-subgraph-2',
            'MOYDOV-subgraph-3', 'NIZQUK-subgraph-1', 'SAYHIJ-subgraph-1', 'CIQGOY-subgraph-0', 'VUFZUT-subgraph-1',
            'ZOQFIU-subgraph-0', 'GUQBUQ-subgraph-0', 'LEZYUM-subgraph-2', 'RAJXUX-subgraph-2', 'QEWZOH-subgraph-3'
        ]
        ligand_charges = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
        ]

    elif space == '1B':

        ligand_names = [
            'JEZBAR-subgraph-3', 'SASKIG-subgraph-0', 'CEPCAE-subgraph-5', 'NEWYIY-subgraph-5', 'UHIMUU-subgraph-1',
            'SEHHIW-subgraph-1', 'ABESAB-subgraph-0', 'ZUQYEP-subgraph-1', 'USESES-subgraph-0', 'IYAMAX-subgraph-2',
            'WOZRAG-subgraph-1', 'PIWZOM-subgraph-0', 'NEJSUT-subgraph-0', 'PAKLUL-subgraph-2', 'AJUBIS-subgraph-1',
            'PAWGOK-subgraph-1', 'VICTAF-subgraph-1', 'PATPUY-subgraph-2', 'EPOWEM-subgraph-1', 'HOVMIP-subgraph-3',
            'LEFREW-subgraph-0', 'TUNGOZ-subgraph-5', 'ZUBJOV-subgraph-0', 'WODCIB-subgraph-2', 'ERUSEQ-subgraph-2',
            'EGUDAM-subgraph-3', 'RAJVEE-subgraph-2', 'ERURAL-subgraph-3', 'IDOTUT-subgraph-1', 'IGUXAJ-subgraph-2',
            'IWOPOZ-subgraph-1', 'GUBZAG-subgraph-0', 'EFOXII-subgraph-5', 'AGAYOX-subgraph-4', 'YUXWAQ-subgraph-1',
            'OHUTAN-subgraph-3', 'BAHZAN-subgraph-1', 'MULYIC-subgraph-1', 'CBFMOP-subgraph-3', 'XIJWOD-subgraph-1',
            'MOVYAZ-subgraph-3', 'MAYZUH-subgraph-1', 'KEZBEY-subgraph-1', 'NAQWUZ-subgraph-4', 'DEYDIW-subgraph-3',
            'YIMKUA-subgraph-1', 'TIDQAY-subgraph-1', 'SOQHIQ-subgraph-4', 'SICNID-subgraph-3', 'TIJQOS-subgraph-0',
            'YAMTEL-subgraph-4', 'HOVMOV-subgraph-2', 'KATREC-subgraph-3', 'BIFXAP-subgraph-2', 'QEBSAT-subgraph-3',
            'AGUFIT-subgraph-1', 'VEZXAA-subgraph-3', 'RUHPOA-subgraph-1', 'OCEPAQ-subgraph-3', 'KAPZIL-subgraph-2',
            'EZOZIE-subgraph-2', 'VABMET-subgraph-3', 'QUHTUI-subgraph-1', 'TIGXAK-subgraph-4', 'OYOPEY-subgraph-2',
            'HAMTOE-subgraph-3', 'IPELOE-subgraph-3', 'BAXCEK-subgraph-2', 'COPSOQ-subgraph-1', 'ETUVAQ-subgraph-1',
            'KAPDEM-subgraph-1', 'YEXCUA-subgraph-1', 'CECVAK-subgraph-3', 'QETYEU-subgraph-2', 'EZAMOH-subgraph-2',
            'ECUZEI-subgraph-3', 'OBIHOX-subgraph-3', 'RIWYUR-subgraph-1', 'DEBCES-subgraph-2', 'UQUFIW-subgraph-1',
            'IGANOT-subgraph-0', 'LABWUG-subgraph-2', 'EYIWIT-subgraph-2', 'GOMXUB-subgraph-1', 'YESFOR-subgraph-2',
            'CILPET-subgraph-4', 'NOCRED-subgraph-3', 'NORHEJ-subgraph-2', 'WONTOK-subgraph-1', 'KURRIZ-subgraph-4',
            'NEKRAX-subgraph-2', 'YUHNUK-subgraph-2', 'VIDFIZ-subgraph-0', 'NIKGIY-subgraph-1', 'TOPVIE-subgraph-0',
            'DEHDOK-subgraph-1', 'KIJYOS-subgraph-3', 'GOMYAI-subgraph-2', 'QETXET-subgraph-1', 'WUFNAM-subgraph-3',
            'KENTOO-subgraph-1', 'NAXWIT-subgraph-1', 'DUGVUX-subgraph-4', 'CTMOPD-subgraph-3', 'BOFHOU-subgraph-5',
            'QEWGIK-subgraph-1', 'XOCKOS-subgraph-1', 'WAJFOC-subgraph-2', 'GEPGEP-subgraph-3', 'DEJCAX-subgraph-3',
            'QETXOD-subgraph-3', 'CEGZUJ-subgraph-1', 'MEFWAY-subgraph-2', 'BIFZIB-subgraph-3', 'XEXLIV-subgraph-2',
            'ECIBEY-subgraph-0', 'ZOMHAN-subgraph-3', 'JOHDIV-subgraph-1', 'TALXOU-subgraph-1', 'POHKON-subgraph-2',
            'WAJNEC-subgraph-3', 'GOMXOV-subgraph-1', 'TECQOI-subgraph-3', 'PARPEG-subgraph-1', 'NOPXOF-subgraph-3',
            'PELWOT-subgraph-3', 'MAZJIJ-subgraph-0', 'CITFOB-subgraph-0', 'HIRTUX-subgraph-1', 'XILTIV-subgraph-2',
            'YEBFUJ-subgraph-2', 'XECDAN-subgraph-1', 'TEYBOP-subgraph-0', 'PZRMSI-subgraph-1', 'JIJPEX-subgraph-2',
            'CEHNAH-subgraph-2', 'UBOWIR-subgraph-0', 'YOHHIM-subgraph-0', 'SAGFOV-subgraph-1', 'MESWOW-subgraph-3',
            'KIBBAB-subgraph-1', 'ZOPYEK-subgraph-1', 'IFEDED-subgraph-0', 'BAPYEW-subgraph-2', 'COVBEU-subgraph-1',
            'MULRER-subgraph-0', 'VAVROC-subgraph-2', 'KIRVEM-subgraph-3', 'ABODUS-subgraph-0', 'SEBTOI-subgraph-0',
            'BIGYIZ-subgraph-1', 'REPYER-subgraph-1', 'OFIBEK-subgraph-3', 'HUZYUW-subgraph-2', 'KUJHII-subgraph-0',
            'PULFEI-subgraph-2', 'MAKJIU-subgraph-3', 'QIRYOG-subgraph-0', 'FIRCER-subgraph-1', 'HEFTIY-subgraph-1',
            'HUTZOM-subgraph-2', 'EPIMEW-subgraph-1', 'WUWHUT-subgraph-1', 'FIHJAI-subgraph-4', 'BAZTEC-subgraph-3',
            'QAYDOJ-subgraph-2', 'GITWOV-subgraph-0', 'GULYAP-subgraph-3', 'BUBSEW-subgraph-3', 'DAPVUL-subgraph-0',
            'FIJFOW-subgraph-1', 'YUKLIA-subgraph-4', 'NIRKAA-subgraph-1', 'TURSIJ-subgraph-1', 'EMIDEL-subgraph-1',
            'JASVAD-subgraph-0', 'RAFJAJ-subgraph-1', 'HOZHUA-subgraph-0', 'JOBBEK-subgraph-2', 'YOSMUP-subgraph-1',
            'EYICIY-subgraph-2', 'UKOTET-subgraph-1', 'QAVJED-subgraph-3', 'CADJOG-subgraph-2', 'BEWTOO-subgraph-1',
            'ZIDQAG-subgraph-0', 'WEKQAE-subgraph-0', 'ABAJAP-subgraph-0', 'WISJEQ-subgraph-1', 'VAMYUF-subgraph-1',
            'ZAGGIA-subgraph-2', 'ATUROW-subgraph-1', 'NOSNEQ-subgraph-0', 'YACVON-subgraph-2', 'QEHYAD-subgraph-1',
            'XEYQOH-subgraph-1', 'NEWYEV-subgraph-3', 'ASINUL-subgraph-0', 'ABOFAA-subgraph-0', 'QOKDIE-subgraph-4',
            'MORLAH-subgraph-0', 'NACTUH-subgraph-2', 'WECGET-subgraph-1', 'QICLAR-subgraph-1', 'ICEFOL-subgraph-0',
            'BOPSAD-subgraph-2', 'AKARIO-subgraph-1', 'RALMOH-subgraph-0', 'OPEREI-subgraph-1', 'KIFWEB-subgraph-2',
            'RAGDIM-subgraph-1', 'OBOBOY-subgraph-3', 'HONPAC-subgraph-3', 'AREKOY-subgraph-3', 'WAYGAG-subgraph-1',
            'QASDAR-subgraph-1', 'BAPDAY-subgraph-1', 'ITIDUK-subgraph-2', 'BAMXIZ-subgraph-1', 'BAQSER-subgraph-2',
            'KESNUU-subgraph-1', 'HICRAN-subgraph-0', 'YOGWAU-subgraph-0', 'PUMDAC-subgraph-1', 'LAYJIG-subgraph-0',
            'NURLES-subgraph-1', 'MUSPEW-subgraph-1', 'UDOPIM-subgraph-3', 'BAZTOM-subgraph-0', 'UWIWUT-subgraph-0',
            'VEJLEB-subgraph-4', 'FOKKEW-subgraph-2', 'VANTUA-subgraph-1', 'TADREY-subgraph-3', 'YIPZOP-subgraph-4',
            'LOKQAD-subgraph-2', 'XEVDAE-subgraph-0', 'TIXLES-subgraph-3', 'QIVHIO-subgraph-1', 'WOCYET-subgraph-1',
            'EGONEU-subgraph-1', 'JEHKIR-subgraph-5', 'DAJLOS-subgraph-1', 'BAHKOL-subgraph-2', 'FIVSIN-subgraph-0',
            'TOPYEE-subgraph-1', 'SIYVOL-subgraph-0', 'OHEHOZ-subgraph-1', 'TUXGEY-subgraph-0', 'WEMKUV-subgraph-2',
            'KOBVAZ-subgraph-0', 'DACCUG-subgraph-2'
        ]
        ligand_charges = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
        ]

    elif space == '1B_rand1':
        
        ligand_names = [
            'DUHDUF-subgraph-1', 'YEDKIE-subgraph-2', 'WAFZEJ-subgraph-3', 'UDOVAN-subgraph-1', 'VORCEN-subgraph-0',
            'HAYXEK-subgraph-3', 'CUDJER-subgraph-0', 'KIVKUX-subgraph-0', 'DOXPOX-subgraph-2', 'TUKWUS-subgraph-0',
            'FANWEX-subgraph-3', 'DACYOW-subgraph-1', 'DAQWAT-subgraph-1', 'MONTEP-subgraph-1', 'DIVNUR-subgraph-5',
            'FUWRUM-subgraph-4', 'NADYAS-subgraph-5', 'KUPFEI-subgraph-2', 'OLEVOQ-subgraph-2', 'BIMHEM-subgraph-0',
            'IJAKUZ-subgraph-3', 'UKAZOW-subgraph-1', 'IYUWAA-subgraph-3', 'VEKCOF-subgraph-1', 'SAQFOI-subgraph-0',
            'KOXPAO-subgraph-3', 'HANJEO-subgraph-2', 'ELUFUO-subgraph-2', 'POZRIF-subgraph-5', 'KAPZIL-subgraph-2',
            'IFAXEU-subgraph-1', 'ZEYGOZ-subgraph-5', 'KEGPAN-subgraph-0', 'MEFVUR-subgraph-2', 'HEPGIT-subgraph-1',
            'CADFET-subgraph-3', 'ASIGUF-subgraph-1', 'VOWFUI-subgraph-2', 'GABMOL-subgraph-0', 'JAMJIT-subgraph-2',
            'AFAMIF-subgraph-0', 'GEGNIQ-subgraph-1', 'SOSXOO-subgraph-0', 'IGIRIA-subgraph-2', 'GIBWEU-subgraph-1',
            'SIFXAG-subgraph-2', 'KOFJUN-subgraph-0', 'BOSFIB-subgraph-2', 'GIHVAV-subgraph-2', 'DEHDOK-subgraph-1',
            'KUHZUI-subgraph-0', 'FISTOS-subgraph-2', 'XARXUL-subgraph-1', 'GAPDOT-subgraph-0', 'EMACCR-subgraph-1',
            'GABDIZ-subgraph-3', 'OVURUU-subgraph-0', 'PEVSUF-subgraph-2', 'KIJGEQ-subgraph-3', 'GENJAK-subgraph-0',
            'KATTOO-subgraph-2', 'GUDQEB-subgraph-5', 'LOLTUC-subgraph-0', 'ACUTEA-subgraph-0', 'EDONOC-subgraph-2',
            'DAHXOB-subgraph-1', 'YEDYOY-subgraph-0', 'VUMWOR-subgraph-2', 'VOVSUW-subgraph-1', 'VEDHAN-subgraph-0',
            'HERBOV-subgraph-2', 'JULMIO-subgraph-0', 'ZOKRUO-subgraph-5', 'BOHZON-subgraph-0', 'UPAMAB-subgraph-1',
            'BEHRIQ-subgraph-4', 'JIQDUL-subgraph-0', 'AQUTUC-subgraph-2', 'ZOMYIJ-subgraph-5', 'DESZUZ-subgraph-3',
            'EYIWEP-subgraph-1', 'TIGVOW-subgraph-5', 'SEWYUQ-subgraph-3', 'QUBVOZ-subgraph-1', 'MEWMEG-subgraph-0',
            'VUPMIE-subgraph-3', 'NOBCAL-subgraph-2', 'DIKVOI-subgraph-2', 'WERFOR-subgraph-3', 'ATOSUY-subgraph-2',
            'VOBXER-subgraph-2', 'MIDBEH-subgraph-1', 'SUHDUU-subgraph-0', 'YEKTAM-subgraph-0', 'QOKPOX-subgraph-3',
            'NOQFIL-subgraph-2', 'WAPGAY-subgraph-5', 'WUPZEN-subgraph-1', 'CUXMIT-subgraph-3', 'BONBIQ-subgraph-2',
            'AFOZIE-subgraph-1', 'BEVKOF-subgraph-2', 'HBUPPT-subgraph-0', 'SEMNAB-subgraph-1', 'IQIHUM-subgraph-1',
            'FUPMOS-subgraph-0', 'XANTAH-subgraph-5', 'VOGYIB-subgraph-2', 'MACHEE-subgraph-0', 'KISMUW-subgraph-1',
            'TUKPIA-subgraph-1', 'UZENET-subgraph-2', 'MOQFEF-subgraph-0', 'NEPVEL-subgraph-2', 'VIMFUU-subgraph-2',
            'SAVFON-subgraph-3', 'MIXMAI-subgraph-1', 'POWJIU-subgraph-3', 'RARNAZ-subgraph-0', 'RUWBAO-subgraph-5',
            'GAMKOW-subgraph-2', 'XIYLEW-subgraph-2', 'VEWBII-subgraph-0', 'TEKKAX-subgraph-0', 'YADQOM-subgraph-3',
            'VAJQAY-subgraph-0', 'VUMMEV-subgraph-2', 'WANZAM-subgraph-3', 'REQCIZ-subgraph-2', 'LIBKEM-subgraph-0',
            'SIHLAY-subgraph-3', 'NENFOB-subgraph-0', 'SAYYOJ-subgraph-0', 'EYEQAC-subgraph-1', 'FUQDEC-subgraph-1',
            'KAGXOG-subgraph-0', 'QAQBOB-subgraph-0', 'XEVDAE-subgraph-0', 'QONHEG-subgraph-3', 'PAYPEL-subgraph-1',
            'FOBZAX-subgraph-0', 'MADSUG-subgraph-0', 'FIHJAI-subgraph-4', 'GIYNEJ-subgraph-0', 'MIBDAE-subgraph-1',
            'EVUHAF-subgraph-3', 'SUVTOU-subgraph-1', 'SODSIN-subgraph-1', 'KEZVAM-subgraph-5', 'OTUREB-subgraph-1',
            'UQEDEA-subgraph-2', 'BETZEH-subgraph-1', 'LOSTUK-subgraph-2', 'LITVAO-subgraph-0', 'YEDSEG-subgraph-0',
            'FACGUN-subgraph-2', 'NUTLET-subgraph-1', 'BELCUR-subgraph-1', 'NEBHEK-subgraph-1', 'ERIBEM-subgraph-1',
            'FUVLOZ-subgraph-0', 'FUGWOT-subgraph-3', 'OSESAI-subgraph-3', 'KISNUX-subgraph-0', 'EPUKIK-subgraph-2',
            'IQINUS-subgraph-0', 'XIWTAZ-subgraph-3', 'UJAKEV-subgraph-1', 'SONJEK-subgraph-2', 'JAHCIE-subgraph-1',
            'RAFJAJ-subgraph-1', 'SODTAJ-subgraph-1', 'MAPJES-subgraph-0', 'HAVQIH-subgraph-1', 'JABZES-subgraph-1',
            'YUCLEP-subgraph-5', 'JEJDAD-subgraph-1', 'PZRMSI-subgraph-1', 'CUNVOW-subgraph-5', 'SOTVAB-subgraph-2',
            'OSOKIS-subgraph-5', 'GAJMEK-subgraph-1', 'TITPES-subgraph-2', 'CIZJUR-subgraph-0', 'SEJZOW-subgraph-0',
            'MOWHAH-subgraph-0', 'QODDEU-subgraph-1', 'CIFZUN-subgraph-3', 'FOFPEW-subgraph-1', 'RAGDIM-subgraph-1',
            'IKUPEK-subgraph-1', 'ZACNUP-subgraph-1', 'BELFOO-subgraph-2', 'KEJPAQ-subgraph-2', 'COCQOB-subgraph-0',
            'OPAGES-subgraph-0', 'SAPSIM-subgraph-2', 'ICUHUJ-subgraph-2', 'EABIMN-subgraph-0', 'VIXSAX-subgraph-1',
            'KENQOM-subgraph-0', 'KAYKAY-subgraph-0', 'QIZREZ-subgraph-1', 'XESROE-subgraph-1', 'BEBWUC-subgraph-1',
            'LIZNUF-subgraph-1', 'TUPPEZ-subgraph-3', 'AYAMAQ-subgraph-3', 'YIDGOK-subgraph-1', 'YAKFOI-subgraph-1',
            'MIRNIL-subgraph-0', 'QAXCUN-subgraph-1', 'JISGEX-subgraph-1', 'PUBKUT-subgraph-1', 'VORVUV-subgraph-2',
            'ZUHZOT-subgraph-0', 'LIVMIN-subgraph-1', 'HOHKIB-subgraph-1', 'ZAPBUN-subgraph-1', 'HUTZOM-subgraph-2',
            'BOBQUE-subgraph-2', 'PIJNOM-subgraph-1', 'HIGNIX-subgraph-1', 'OLOSOZ-subgraph-1', 'ICERIR-subgraph-2',
            'MOMCIC-subgraph-0', 'IZILOU-subgraph-1', 'TERHII-subgraph-0', 'MABSIT-subgraph-1', 'RIHFAR-subgraph-2',
            'KAKYUQ-subgraph-0', 'EJAYOE-subgraph-0', 'LEDSIX-subgraph-1', 'ATUQOV-subgraph-0', 'XUTTUB-subgraph-3',
            'ACEYNI-subgraph-2', 'TPFECO-subgraph-4', 'NOBJIZ-subgraph-4', 'PIFZAF-subgraph-0', 'MAPKOD-subgraph-0',
            'CEPPAR-subgraph-1', 'JIQMAX-subgraph-1', 'JIRLIG-subgraph-0', 'UCURUG-subgraph-0', 'BAHKOL-subgraph-2',
            'ICOBAE-subgraph-1', 'JOGSAZ-subgraph-0', 'NUXRAB-subgraph-0', 'HEQXEJ-subgraph-1', 'WOSVOP-subgraph-2',
            'PUJVEX-subgraph-3', 'JUXREZ-subgraph-1'
        ]
        ligand_charges = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
        ]
    elif space == '1B_rand2':
        
        ligand_names = [
            'NOZFIR-subgraph-0', 'VIGXAM-subgraph-0', 'OWEPUC-subgraph-3', 'ATUREM-subgraph-2', 'OHUTAN-subgraph-3',
            'HARPIZ-subgraph-1', 'ROCQAC-subgraph-0', 'QOKYAQ-subgraph-2', 'SIFBUG-subgraph-1', 'QIGCOA-subgraph-2',
            'XUBMEO-subgraph-0', 'HOXKAG-subgraph-1', 'GALFII-subgraph-2', 'TAWNEN-subgraph-0', 'WUTPEI-subgraph-1',
            'NOLGED-subgraph-1', 'VEZHAK-subgraph-2', 'GEYYUG-subgraph-1', 'HAJWAS-subgraph-0', 'YAMFAU-subgraph-2',
            'XUZZOH-subgraph-0', 'PARPEG-subgraph-1', 'TORBEJ-subgraph-1', 'YULCOY-subgraph-0', 'ACETUX-subgraph-1',
            'AFANEC-subgraph-2', 'REFRAV-subgraph-0', 'RUZBUK-subgraph-3', 'GEDXOC-subgraph-5', 'SANMOJ-subgraph-1',
            'RAXQAI-subgraph-0', 'ECUZEI-subgraph-3', 'TALDUI-subgraph-1', 'QUVXEL-subgraph-2', 'SAJQEA-subgraph-0',
            'QANQAA-subgraph-1', 'BIMRIY-subgraph-0', 'XAPDIB-subgraph-3', 'BEJGOM-subgraph-1', 'AFUSEZ-subgraph-3',
            'XALFEV-subgraph-5', 'KIBPAN-subgraph-1', 'KUWLAR-subgraph-0', 'SEWNUE-subgraph-5', 'SOPVIC-subgraph-0',
            'EDEXIX-subgraph-1', 'PATKEC-subgraph-1', 'IPEMAR-subgraph-0', 'RUVZOZ-subgraph-5', 'WOPMIA-subgraph-0',
            'OMELAU-subgraph-1', 'NIHTUT-subgraph-3', 'ZAHYIT-subgraph-1', 'TEQYOF-subgraph-3', 'LALGAG-subgraph-2',
            'KIJFOZ-subgraph-3', 'ZODQUE-subgraph-1', 'WESPIW-subgraph-0', 'ICPNMN-subgraph-1', 'TIRFUY-subgraph-0',
            'LUSDUA-subgraph-0', 'ZAPLEH-subgraph-2', 'YECKIC-subgraph-1', 'MUJVUK-subgraph-0', 'COJBEK-subgraph-1',
            'RUQHIV-subgraph-2', 'IXIXUJ-subgraph-2', 'SINFUQ-subgraph-4', 'LICCEF-subgraph-0', 'YARFEC-subgraph-0',
            'LUWRIE-subgraph-2', 'EPADUW-subgraph-1', 'YIKXUM-subgraph-1', 'CHVICR-subgraph-1', 'DISFIU-subgraph-3',
            'TAXJIM-subgraph-0', 'PESJIJ-subgraph-3', 'SOWDIR-subgraph-0', 'SAXDAY-subgraph-3', 'FIBLOS-subgraph-0',
            'CORPAD-subgraph-1', 'CUFPOI-subgraph-0', 'ROBGOG-subgraph-1', 'KEDQOA-subgraph-1', 'MIMHEY-subgraph-2',
            'QABMIP-subgraph-1', 'UBOCAP-subgraph-2', 'TIQTAO-subgraph-3', 'FOFYAA-subgraph-0', 'WEFPOM-subgraph-0',
            'AQERIY-subgraph-3', 'VOVQUU-subgraph-0', 'IDOSOJ-subgraph-0', 'RUFLEJ-subgraph-3', 'USEYOH-subgraph-1',
            'GUVKIT-subgraph-3', 'ZOBPAK-subgraph-1', 'HEZQAG-subgraph-0', 'YITVOM-subgraph-1', 'CILPIZ-subgraph-1',
            'LAJTUL-subgraph-1', 'QONSAO-subgraph-0', 'EWULAJ-subgraph-0', 'QIJGOF-subgraph-0', 'DUXFUZ-subgraph-0',
            'INENOF-subgraph-1', 'TABXOJ-subgraph-0', 'ISAKAP-subgraph-0', 'DAQJAI-subgraph-1', 'XUNRII-subgraph-0',
            'JODGIV-subgraph-3', 'EFOXEF-subgraph-1', 'LAHYUO-subgraph-3', 'FOGQEX-subgraph-2', 'JAHCAW-subgraph-2',
            'YOMTUR-subgraph-3', 'EFOBUW-subgraph-2', 'HIBNOY-subgraph-1', 'YAKLUR-subgraph-0', 'HIXXOB-subgraph-2',
            'ISEPIH-subgraph-1', 'WIRHOU-subgraph-2', 'JESGEU-subgraph-1', 'QUHZID-subgraph-1', 'SAGJEP-subgraph-3',
            'PUJMAK-subgraph-0', 'NEKLIZ-subgraph-3', 'MOFKEX-subgraph-4', 'RIBSAX-subgraph-1', 'RAXQIQ-subgraph-2',
            'ROBPII-subgraph-1', 'SATGEC-subgraph-0', 'MOWWUR-subgraph-0', 'BAPDAY-subgraph-1', 'RECDAG-subgraph-1',
            'LOVPIV-subgraph-5', 'IVOJEI-subgraph-0', 'CAQNOZ-subgraph-1', 'ASANIS-subgraph-3', 'FEPKIX-subgraph-2',
            'LABXIW-subgraph-1', 'TESGAB-subgraph-0', 'YUKLIA-subgraph-4', 'UDAKAM-subgraph-1', 'NUMNAL-subgraph-0',
            'IPUYIB-subgraph-0', 'AMIQIX-subgraph-0', 'XEHVAJ-subgraph-1', 'REDGAJ-subgraph-0', 'ZESKOK-subgraph-2',
            'XILHAB-subgraph-0', 'GOXFII-subgraph-4', 'TIGXIQ-subgraph-0', 'BARQER-subgraph-0', 'REFTOO-subgraph-3',
            'VAVSEQ-subgraph-1', 'YAKFEY-subgraph-0', 'ADUROH-subgraph-1', 'YORTOP-subgraph-1', 'REZCAA-subgraph-1',
            'QAQTOS-subgraph-2', 'SUVTUA-subgraph-0', 'WIHVEQ-subgraph-3', 'SICFEA-subgraph-0', 'VIHLEF-subgraph-4',
            'DOCYOL-subgraph-2', 'JOHNIE-subgraph-3', 'JANLIW-subgraph-2', 'KEWCOH-subgraph-0', 'NOMJOP-subgraph-3',
            'PAQPED-subgraph-2', 'AHASAF-subgraph-0', 'OBOSAZ-subgraph-0', 'PIJHEV-subgraph-0', 'QAPSOP-subgraph-1',
            'IQIWAG-subgraph-1', 'OPEREI-subgraph-1', 'SANFAO-subgraph-3', 'LUFHOL-subgraph-3', 'IGUGUO-subgraph-1',
            'WAQWEQ-subgraph-2', 'MINYAL-subgraph-1', 'RAZKAE-subgraph-0', 'NOSNIU-subgraph-1', 'BEMBIE-subgraph-3',
            'PIBNEV-subgraph-0', 'NEGWEE-subgraph-1', 'WAYNIW-subgraph-1', 'ATECUY-subgraph-0', 'RATJAA-subgraph-0',
            'UGAQEA-subgraph-0', 'PERPIO-subgraph-1', 'JASGAM-subgraph-0', 'YAMXOA-subgraph-0', 'MINXOY-subgraph-1',
            'MURTUP-subgraph-3', 'MOMBUN-subgraph-0', 'FELSUN-subgraph-0', 'QIFXAG-subgraph-2', 'JOBBEK-subgraph-2',
            'COFWOJ-subgraph-0', 'LEGXEA-subgraph-1', 'ZECGAS-subgraph-0', 'HISREJ-subgraph-0', 'HICRAN-subgraph-0',
            'YIHPAI-subgraph-1', 'NASKUO-subgraph-1', 'XUVKUV-subgraph-3', 'VUFYIG-subgraph-3', 'TIPXIZ-subgraph-3',
            'AJIGAC-subgraph-0', 'SIDNIE-subgraph-0', 'QIJYUG-subgraph-0', 'JIPPEG-subgraph-1', 'YERWEX-subgraph-2',
            'NACTUH-subgraph-2', 'NIHRIH-subgraph-0', 'EKIGEM-subgraph-3', 'JIWSAJ-subgraph-0', 'REDLAQ-subgraph-0',
            'JEWBUL-subgraph-1', 'YINNIS-subgraph-0', 'ICEFOL-subgraph-0', 'RAKGIV-subgraph-0', 'VABYUT-subgraph-2',
            'AQULUT-subgraph-0', 'IYUDOV-subgraph-0', 'WIJCIC-subgraph-1', 'SICSAZ-subgraph-1', 'KEJPEV-subgraph-2',
            'YEFKOJ-subgraph-3', 'EDAXOY-subgraph-1', 'COCSET-subgraph-0', 'NEDNIU-subgraph-0', 'RICLUK-subgraph-0',
            'GEQXAC-subgraph-2', 'IZIDAW-subgraph-0', 'DOCRUJ-subgraph-1', 'ROBRAB-subgraph-1', 'CUSREN-subgraph-3',
            'DEFGAZ-subgraph-3', 'RUQNOI-subgraph-1', 'JITSAG-subgraph-1', 'WASQUC-subgraph-0', 'IKESIB-subgraph-1',
            'ITIFEY-subgraph-2', 'YUCKOY-subgraph-5', 'ZUJWUY-subgraph-2', 'BEQFIO-subgraph-1', 'JADVIW-subgraph-0',
            'HAMQOB-subgraph-1', 'DACCOA-subgraph-0'
        ]
        ligand_charges = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
        ]

    elif space == '1B_rand3':
        
        ligand_names = [
            'FOSFID-subgraph-3', 'HIWJON-subgraph-0', 'BIYJAU-subgraph-3', 'GECHOO-subgraph-0', 'FOSZOD-subgraph-1',
            'JUSROG-subgraph-2', 'RAZLOW-subgraph-0', 'YUJZUA-subgraph-2', 'ZOJJUD-subgraph-2', 'ASIGOZ-subgraph-1',
            'REFCIQ-subgraph-2', 'SAWHUU-subgraph-1', 'LORVUL-subgraph-5', 'PESDUN-subgraph-2', 'DARVOI-subgraph-0',
            'NECVAV-subgraph-0', 'NEGDUZ-subgraph-1', 'MAFYOK-subgraph-0', 'HIXZEU-subgraph-0', 'BOQQOQ-subgraph-2',
            'SAQLAA-subgraph-2', 'LEFREW-subgraph-0', 'GIPQAA-subgraph-1', 'MOCFUH-subgraph-3', 'LAHTUJ-subgraph-4',
            'SIFCAN-subgraph-3', 'KEWDAU-subgraph-0', 'ALUNOM-subgraph-1', 'MOHPIJ-subgraph-0', 'MEWXAQ-subgraph-4',
            'NUYYIR-subgraph-2', 'QIWWID-subgraph-1', 'OCEBUW-subgraph-0', 'QIDKUL-subgraph-1', 'MOZFEO-subgraph-0',
            'CUTHOP-subgraph-0', 'QONTES-subgraph-5', 'RAMRED-subgraph-0', 'CUDJAN-subgraph-2', 'GUKGAW-subgraph-1',
            'QUWPOO-subgraph-0', 'JEDLAI-subgraph-3', 'QOZBIS-subgraph-1', 'ROBGOH-subgraph-4', 'JUJSUC-subgraph-2',
            'YOQBOW-subgraph-1', 'TUDREQ-subgraph-3', 'COPPUT-subgraph-0', 'UNAMIF-subgraph-5', 'LOPPEL-subgraph-0',
            'XANGEB-subgraph-2', 'ZIWBUF-subgraph-2', 'SATJIJ-subgraph-1', 'DOXMEI-subgraph-1', 'NUZXEM-subgraph-2',
            'IWAYUC-subgraph-0', 'IGAKEJ-subgraph-1', 'CEVKUJ-subgraph-0', 'GUTNOZ-subgraph-1', 'EVOGUT-subgraph-0',
            'TAVROZ-subgraph-1', 'JALGIN-subgraph-1', 'MUVPAW-subgraph-1', 'SEGRUT-subgraph-0', 'HOCDEJ-subgraph-0',
            'HILMEW-subgraph-3', 'CUJHAS-subgraph-0', 'BOFROF-subgraph-2', 'JIZKAH-subgraph-0', 'GEQNIA-subgraph-2',
            'ZIZHEX-subgraph-1', 'RIZNUL-subgraph-0', 'PUTKOG-subgraph-2', 'IGUXAK-subgraph-1', 'FOSFOJ-subgraph-2',
            'BEJFIG-subgraph-0', 'ADETIO-subgraph-1', 'EGUDAM-subgraph-3', 'TABSOF-subgraph-5', 'LUGRAI-subgraph-1',
            'ROWWIL-subgraph-1', 'SOTFOY-subgraph-0', 'IXOKUB-subgraph-5', 'VIXSOL-subgraph-1', 'POCDUG-subgraph-1',
            'IXEHOJ-subgraph-3', 'LIWVAR-subgraph-0', 'NAHMEQ-subgraph-1', 'YULCAK-subgraph-0', 'COHMIW-subgraph-0',
            'MAXGIC-subgraph-2', 'EHUSUV-subgraph-0', 'BUTZUM-subgraph-1', 'NOZHOB-subgraph-0', 'KIYSOA-subgraph-1',
            'DIHVEY-subgraph-1', 'XOPFUD-subgraph-0', 'YORXOT-subgraph-1', 'CAPSOB-subgraph-5', 'XUWGUR-subgraph-0',
            'ZOMJET-subgraph-1', 'GALNUF-subgraph-1', 'QEHCEN-subgraph-1', 'HEBDOI-subgraph-0', 'WODSIR-subgraph-5',
            'KATREC-subgraph-3', 'AMAZOE-subgraph-1', 'QEHLIA-subgraph-3', 'SODFAV-subgraph-2', 'BOJPOI-subgraph-0',
            'FUTHOR-subgraph-3', 'UMAGUL-subgraph-1', 'YETLEO-subgraph-0', 'GEHQEQ-subgraph-1', 'GAYVOR-subgraph-1',
            'POWCEJ-subgraph-1', 'MOWGIQ-subgraph-1', 'JAWZAJ-subgraph-3', 'AVACIJ-subgraph-1', 'IWAZUB-subgraph-0',
            'OMINAZ-subgraph-0', 'COFWUR-subgraph-0', 'TIWYUW-subgraph-0', 'JEYZAP-subgraph-2', 'ZOSSOS-subgraph-1',
            'VALFEV-subgraph-2', 'HOGFER-subgraph-0', 'CERWOL-subgraph-5', 'AYIGEW-subgraph-1', 'KOCGAL-subgraph-2',
            'WACMUJ-subgraph-1', 'DAMBUO-subgraph-3', 'SENDUM-subgraph-3', 'LIVYUK-subgraph-1', 'OWUHEU-subgraph-0',
            'EPOMOM-subgraph-1', 'QORLIS-subgraph-1', 'NOWHEO-subgraph-2', 'XUKGOZ-subgraph-1', 'CECHIE-subgraph-1',
            'INIJIY-subgraph-0', 'UFENAX-subgraph-1', 'UHEDAN-subgraph-0', 'RUGTAP-subgraph-0', 'BONRIF-subgraph-0',
            'SIJKEB-subgraph-0', 'VEGGIY-subgraph-0', 'ATUROW-subgraph-2', 'XUKGUF-subgraph-1', 'IVUNAQ-subgraph-2',
            'URUKOI-subgraph-0', 'WEMKUV-subgraph-2', 'WEHSOS-subgraph-1', 'ZIHBEX-subgraph-1', 'FIRCER-subgraph-1',
            'FEKQEU-subgraph-0', 'ODOGOF-subgraph-2', 'XAKGUL-subgraph-1', 'RASKAX-subgraph-1', 'IBIHAC-subgraph-0',
            'FIHKEM-subgraph-2', 'AGITOA-subgraph-0', 'ICERUD-subgraph-2', 'EGADAU-subgraph-3', 'RAXVAN-subgraph-0',
            'WOSVIJ-subgraph-2', 'PIJLIE-subgraph-1', 'LOGNEA-subgraph-0', 'GIXFEY-subgraph-1', 'VAMYUF-subgraph-1',
            'ORUCAG-subgraph-3', 'NEDFUY-subgraph-1', 'VAXMOX-subgraph-2', 'FADJUP-subgraph-3', 'WAYHOW-subgraph-0',
            'EVAGUD-subgraph-0', 'LEHQOE-subgraph-1', 'YIDFUP-subgraph-1', 'UMUTUR-subgraph-0', 'AJIJAF-subgraph-0',
            'GULXOC-subgraph-3', 'PAKVUU-subgraph-0', 'YIQQAQ-subgraph-1', 'TARNIJ-subgraph-1', 'SIXBUY-subgraph-1',
            'MOVYAZ-subgraph-4', 'WAJYAK-subgraph-3', 'SADHAG-subgraph-3', 'FILVIG-subgraph-1', 'DECSOW-subgraph-1',
            'DOPWAH-subgraph-1', 'QOJSOX-subgraph-0', 'MICZUV-subgraph-0', 'UDOPIM-subgraph-3', 'BIGYIZ-subgraph-1',
            'QARDAQ-subgraph-0', 'NORYUO-subgraph-2', 'FUJLUT-subgraph-0', 'BOFGOS-subgraph-1', 'OZEVOF-subgraph-2',
            'WAYJIS-subgraph-0', 'GUVQUJ-subgraph-0', 'LEXKAB-subgraph-1', 'LAJTEW-subgraph-3', 'SENFAU-subgraph-2',
            'JAFKAF-subgraph-2', 'RELWEM-subgraph-0', 'DUKBIW-subgraph-1', 'FIHYIF-subgraph-2', 'GORREM-subgraph-0',
            'BUBCEI-subgraph-0', 'TEGZUD-subgraph-1', 'NEXFOL-subgraph-2', 'LEDVAS-subgraph-0', 'WIBTAD-subgraph-2',
            'XOJRAP-subgraph-0', 'DEDKII-subgraph-5', 'FUWXOM-subgraph-0', 'FELJIR-subgraph-0', 'YEPSIV-subgraph-2',
            'ZOBKIN-subgraph-0', 'KEVYER-subgraph-1', 'MIYWUM-subgraph-0', 'XEDKAT-subgraph-1', 'TORXUT-subgraph-4',
            'VAVQUE-subgraph-1', 'PIYNOC-subgraph-0', 'WULFIT-subgraph-1', 'SUQTAZ-subgraph-4', 'UHOJOS-subgraph-1',
            'POKRAJ-subgraph-0', 'IPEPUQ-subgraph-1', 'KUPQAP-subgraph-0', 'AREJUD-subgraph-3', 'VEFSUX-subgraph-2',
            'FIDPIT-subgraph-1', 'UQINAL-subgraph-0', 'ERAZUU-subgraph-3', 'ACITEO-subgraph-1', 'FIHTOF-subgraph-1',
            'ALOBUY-subgraph-3', 'UQUZEM-subgraph-0', 'TIZKAR-subgraph-0', 'BIQTOM-subgraph-0', 'HISRAF-subgraph-0',
            'WILHOR-subgraph-0', 'SISRUK-subgraph-2', 'ZAJLAX-subgraph-1', 'PUDBAR-subgraph-1', 'YAXFOS-subgraph-0',
            'RIWYON-subgraph-0', 'MEXXES-subgraph-3'
        ]

        
        ligand_charges = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
        ]
    else:
        raise Exception('Space name not recognized.')
    
    return ligand_names, ligand_charges